"""Shared data models used across all agents and the data layer."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class MarketStatus(str, Enum):
    ACTIVE = "active"
    CLOSED = "closed"
    RESOLVED = "resolved"


class Token(BaseModel):
    token_id: str
    outcome: str


class Market(BaseModel):
    """Core market representation from Gamma API."""

    condition_id: str
    question: str
    slug: str
    tokens: list[Token] = Field(default_factory=list)
    status: MarketStatus = MarketStatus.ACTIVE
    volume: float = 0.0
    liquidity: float = 0.0
    end_date: datetime | None = None
    tags: list[str] = Field(default_factory=list)


class OrderBookSnapshot(BaseModel):
    """Point-in-time order book from CLOB."""

    token_id: str
    timestamp: datetime
    bids: list[tuple[float, float]] = Field(default_factory=list)  # (price, size)
    asks: list[tuple[float, float]] = Field(default_factory=list)
    midpoint: float = 0.0
    spread: float = 0.0


class Opportunity(BaseModel):
    """Scanner output: a tagged and scored opportunity."""

    market: Market
    score: float  # 0–100
    reasons: list[str] = Field(default_factory=list)
    missing_data: list[str] = Field(default_factory=list)
    orderbook: OrderBookSnapshot | None = None
    detected_at: datetime = Field(default_factory=datetime.utcnow)


class SourceEntry(BaseModel):
    url: str
    title: str
    source_type: str  # "repo", "paper", "blog", "docs", "news"
    relevance: str
    pros: list[str] = Field(default_factory=list)
    cons: list[str] = Field(default_factory=list)
    last_updated: datetime | None = None
    license: str | None = None


class SourceDossier(BaseModel):
    """Research Agent output for a given market."""

    market_id: str
    sources: list[SourceEntry] = Field(default_factory=list)
    summary: str = ""
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class AgentMessage(BaseModel):
    """Message passed between agents on the bus."""

    sender: str
    recipient: str  # agent name or "__broadcast__"
    msg_type: str  # "watchlist", "research_request", "dossier", "command", etc.
    payload: dict = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    correlation_id: str = Field(default_factory=lambda: uuid4().hex[:12])


# === Phase 2: Strategy & Backtesting Models ===


class SignalType(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class MarketSignal(BaseModel):
    """Trading signal generated by Strategy Engineer."""

    signal_type: SignalType
    token_id: str
    market_id: str
    confidence: float  # 0-1
    entry_price: float
    reasoning: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class StrategyType(str, Enum):
    MEAN_REVERSION = "mean_reversion"
    MOMENTUM = "momentum"
    ARBITRAGE = "arbitrage"
    LIQUIDITY_PROVISION = "liquidity_provision"


class EntryRule(BaseModel):
    """Entry condition for a strategy."""

    condition: str  # e.g., "spread > 0.05", "volume_24h > 100000"
    threshold: float
    operator: str  # ">", "<", ">=", "<=", "=="


class ExitRule(BaseModel):
    """Exit condition for a strategy."""

    condition: str  # e.g., "profit_pct > 5", "time_elapsed > 86400"
    threshold: float
    operator: str


class Strategy(BaseModel):
    """Trading strategy generated by Strategy Engineer."""

    strategy_id: str = Field(default_factory=lambda: uuid4().hex[:12])
    strategy_type: StrategyType
    market_id: str
    token_id: str
    entry_rules: list[EntryRule] = Field(default_factory=list)
    exit_rules: list[ExitRule] = Field(default_factory=list)
    position_size: float  # fraction of capital (0-1)
    max_loss_pct: float = 10.0  # stop loss %
    max_gain_pct: float = 50.0  # take profit %
    description: str = ""
    confidence: float = 0.0  # 0-1
    created_at: datetime = Field(default_factory=datetime.utcnow)


class BacktestTrade(BaseModel):
    """Individual trade in a backtest."""

    entry_time: datetime
    exit_time: datetime
    entry_price: float
    exit_price: float
    position_size: float
    pnl: float
    pnl_pct: float
    reason: str  # exit reason


class BacktestResult(BaseModel):
    """Results from backtesting a strategy."""

    strategy_id: str
    start_date: datetime
    end_date: datetime
    initial_capital: float
    final_capital: float
    total_pnl: float
    total_pnl_pct: float
    
    # Performance metrics
    num_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0  # %
    avg_win: float = 0.0
    avg_loss: float = 0.0
    profit_factor: float = 0.0  # gross_profit / gross_loss
    
    # Risk metrics
    max_drawdown: float = 0.0  # %
    max_drawdown_duration_days: int = 0
    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0
    
    # Trade details
    trades: list[BacktestTrade] = Field(default_factory=list)
    
    # Metadata
    backtested_at: datetime = Field(default_factory=datetime.utcnow)
